name: Next.js CI/CD - chitram

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: chitram

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.8'  # Specify your Node.js version here (adjust if needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run tests (optional)
      # If you're using a testing framework like Jest, you can add a test step here.
      # - name: Run tests
      #   run: |
      #     npm test  # Adjust this command if you're using a different testing framework

      # Step 5: Build the app
      - name: Build Next.js app
        run: |
          hostname -I
          nohup npm run dev &  # Run the Next.js dev server in the background
          exit 0  # Exit with a 0 status to ensure the step doesn't fail

      # Optionally, add a step to wait for the app to be fully started if needed
      # - name: Wait for Next.js app to start
      #   run: |
      #     sleep 10  # Wait for 10 seconds (adjust as necessary)
      #     curl --silent --fail http://localhost:3000 || exit 1  # Ensure the app is up by making a request

      # Step 6: Deploy to Vercel (or other hosting services)
      # If you're using Vercel for deployment, you can use their official action:
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
